"""Every user-facing string, English then Italian.

Edit here, then run `python3 tools/gen_strings.py` to rebuild App/Resources/Localizable.xcstrings.
`--check` fails if the catalogue is stale or an enum case has no string.
Italian is machine-assisted and marked for review before any public release.
UK English: calm, plain, second person, no exclamation marks.
"""

S = {
    # Checks
    "check.connection": ("Connection", "Connessione"),
    "check.wifi": ("Wi-Fi signal", "Segnale Wi-Fi"),
    "check.hop": ("Mac to router", "Mac → router"),
    "check.internet": ("Internet latency", "Latenza internet"),
    "check.udp": ("Game traffic (UDP)", "Traffico di gioco (UDP)"),
    "check.ipv6": ("IPv6", "IPv6"),
    "check.speed": ("Speed under load", "Velocità sotto carico"),
    "check.lineFree": ("Line free", "Linea libera"),
    "check.mac": ("This Mac", "Questo Mac"),
    "check.apps": ("Background apps", "App in background"),
    "check.checklist": ("Checklist", "Checklist"),

    # Findings
    "finding.ethernet": ("Wired with a cable. The steadiest way to play.", "Collegato via cavo. Il modo più stabile per giocare."),
    "finding.wifi6GHz": ("Wi-Fi on 6 GHz. Good, though a cable is steadier.", "Wi-Fi a 6 GHz. Bene, ma il cavo è più stabile."),
    "finding.wifi5GHz": ("Wi-Fi on 5 GHz. Fine, though a cable is steadier.", "Wi-Fi a 5 GHz. Va bene, ma il cavo è più stabile."),
    "finding.wifi24GHz": ("Wi-Fi on 2.4 GHz, which is crowded and slow. Join the 5 or 6 GHz network, or plug in a cable.", "Wi-Fi a 2,4 GHz, affollato e lento. Usa la rete a 5 o 6 GHz, oppure un cavo."),
    "finding.notConnected": ("Not connected to a network.", "Non connesso a una rete."),
    "finding.wifiStrong": ("Strong signal and a fast link.", "Segnale forte e collegamento veloce."),
    "finding.wifiWeak": ("The signal is a little weak. Moving closer to the router helps.", "Il segnale è un po' debole. Avvicinarsi al router aiuta."),
    "finding.wifiPoor": ("The signal is weak. Move closer to the router or use a cable.", "Il segnale è debole. Avvicinati al router o usa un cavo."),
    "finding.wifiUnknown": ("Couldn't read the Wi-Fi details.", "Impossibile leggere i dettagli del Wi-Fi."),
    "finding.hopSteady": ("Your Mac's link to the router is steady.", "Il collegamento del Mac al router è stabile."),
    "finding.hopSpiky": ("Your Mac's Wi-Fi has small pauses. Game Mode usually fixes this.", "Il Wi-Fi del Mac ha piccole pause. Di solito la Modalità gioco le risolve."),
    "finding.hopPausing": ("Your Mac's Wi-Fi keeps pausing. Turn on Game Mode, or plug in a cable.", "Il Wi-Fi del Mac continua a fermarsi. Attiva la Modalità gioco o usa un cavo."),
    "finding.hopLoss": ("Packets are getting lost between your Mac and the router.", "Si perdono pacchetti tra il Mac e il router."),
    "finding.internetGood": ("Low and steady latency.", "Latenza bassa e stabile."),
    "finding.internetSlowish": ("Latency is a little high or uneven.", "La latenza è un po' alta o irregolare."),
    "finding.internetPoor": ("Latency is high or jumping around. Expect lag.", "La latenza è alta o instabile. Possibili ritardi."),
    "finding.internetLoss": ("Packets are getting lost on the internet side.", "Si perdono pacchetti lato internet."),
    "finding.udpClean": ("Game traffic gets through without loss.", "Il traffico di gioco passa senza perdite."),
    "finding.udpSomeLoss": ("A little game traffic is getting lost.", "Una piccola parte del traffico di gioco si perde."),
    "finding.udpLossy": ("Game traffic is getting lost. Expect stutter.", "Il traffico di gioco si perde. Possibili scatti."),
    "finding.udpSlow": ("Game traffic is slow to come back.", "Il traffico di gioco torna lentamente."),
    "finding.ipv6Ready": ("IPv6 works, so games can use the more direct route.", "IPv6 funziona: i giochi possono usare il percorso più diretto."),
    "finding.ipv6Missing": ("No IPv6. Not a problem, just one route fewer.", "Niente IPv6. Non è un problema, solo un percorso in meno."),
    "finding.speedGood": ("Plenty of speed, and latency stays low under load.", "Velocità abbondante e latenza bassa anche sotto carico."),
    "finding.speedBloatMild": ("Latency rises when the line is busy. Smart Queues (SQM) on the router helps.", "La latenza sale quando la linea è occupata. Smart Queues (SQM) sul router aiuta."),
    "finding.speedBloatBad": ("Latency jumps when the line is busy. Turn on Smart Queues (SQM) on the router.", "La latenza schizza quando la linea è occupata. Attiva Smart Queues (SQM) sul router."),
    "finding.speedSlow": ("Speed is on the low side for high quality.", "La velocità è bassa per l'alta qualità."),
    "finding.speedTooSlow": ("Too slow for smooth streaming. Lower the stream quality.", "Troppo lenta per uno streaming fluido. Abbassa la qualità."),
    "finding.speedRateLimited": ("The speed test server asked us to wait. Try again in a few minutes.", "Il server del test ha chiesto di attendere. Riprova tra qualche minuto."),
    "finding.lineQuiet": ("Nothing else seems to be using the line.", "Nient'altro sembra usare la linea."),
    "finding.lineMaybeBusy": ("Someone else may be using the line.", "Qualcun altro potrebbe usare la linea."),
    "finding.lineBusy": ("Something else is using the line right now. Downloads and updates cause lag.", "Qualcos'altro sta usando la linea. Download e aggiornamenti causano ritardi."),
    "finding.macReady": ("Ready: on power, cool and not busy.", "Pronto: in carica, fresco e non occupato."),
    "finding.awdlOn": ("AirDrop and Handoff are on. They pause the Wi-Fi now and then. Game Mode switches them off.", "AirDrop e Handoff sono attivi e fermano il Wi-Fi ogni tanto. La Modalità gioco li spegne."),
    "finding.lowPowerOn": ("Low Power Mode is on. It slows the Mac down.", "La modalità Risparmio energetico è attiva e rallenta il Mac."),
    "finding.onBattery": ("Running on battery. Plug in for steadier performance.", "Funziona a batteria. Collega l'alimentatore per prestazioni stabili."),
    "finding.batteryLow": ("The battery is getting low. Plug in.", "La batteria si sta scaricando. Collega l'alimentatore."),
    "finding.thermalHigh": ("Your Mac is hot and may slow down.", "Il Mac è caldo e potrebbe rallentare."),
    "finding.cpuBusy": ("Your Mac is busy with something else.", "Il Mac è occupato con altro."),
    "finding.appsQuiet": ("No background apps that get in the way.", "Nessuna app in background che disturba."),
    "finding.appsNoisy": ("Some apps can disturb the stream. Game Mode quits them.", "Alcune app possono disturbare lo streaming. La Modalità gioco le chiude."),
    "finding.timeMachineRunning": ("A Time Machine backup is running. Game Mode pauses it.", "È in corso un backup di Time Machine. La Modalità gioco lo mette in pausa."),
    "finding.checklistDone": ("Every item on the checklist is done.", "Tutti i punti della checklist sono fatti."),
    "finding.checklistOpen": ("A few settings on the checklist are still open.", "Alcune impostazioni della checklist sono ancora da fare."),
    "finding.notMeasured": ("Couldn't measure this.", "Impossibile misurarlo."),

    # Verdict
    "verdict.ready.title": ("Ready to play", "Pronto per giocare"),
    "verdict.ready.subtitle": ("Everything looks good.", "È tutto a posto."),
    "verdict.warning.title": ("Ready, with a warning", "Pronto, con un avviso"),
    "verdict.warning.subtitle": ("You can play. One thing could be better.", "Puoi giocare. Una cosa potrebbe andare meglio."),
    "verdict.notReady.title": ("Not ready", "Non pronto"),
    "verdict.notReady.subtitle": ("Something will cause lag. See why below.", "Qualcosa causerà ritardi. Vedi sotto."),
    "verdict.incomplete.title": ("Couldn't finish the check", "Controllo non completato"),
    "verdict.incomplete.subtitle": ("Part of the check didn't run. Try again.", "Una parte del controllo non è stata eseguita. Riprova."),
    "verdict.none.title": ("Check before you play", "Controlla prima di giocare"),
    "verdict.none.subtitle": ("About a minute. It tests your Mac, Wi-Fi and internet.", "Circa un minuto. Controlla Mac, Wi-Fi e internet."),

    # Grades (accessibility)
    "grade.green": ("good", "bene"),
    "grade.amber": ("could be better", "migliorabile"),
    "grade.red": ("needs attention", "da sistemare"),
    "grade.unknown": ("not measured", "non misurato"),

    # Steps
    "step.connection": ("Looking at the connection", "Controllo la connessione"),
    "step.hop": ("Testing the Wi-Fi hop", "Provo il collegamento al router"),
    "step.internet": ("Measuring internet latency", "Misuro la latenza internet"),
    "step.udp": ("Testing game traffic", "Provo il traffico di gioco"),
    "step.mac": ("Checking this Mac", "Controllo questo Mac"),
    "step.speed": ("Running the speed test", "Eseguo il test di velocità"),

    # Live events
    "event.spike": ("Latency spike", "Picco di latenza"),
    "event.loss": ("Packet lost", "Pacchetto perso"),
    "event.linkChanged": ("Wi-Fi changed channel", "Il Wi-Fi ha cambiato canale"),
    "event.awdlBack": ("AirDrop radio came back", "La radio di AirDrop si è riattivata"),
    "event.cpuBusy": ("Mac busy", "Mac occupato"),
    "event.thermalHigh": ("Mac hot", "Mac caldo"),
    "event.noisyAppStarted": ("A background app started", "È partita un'app in background"),
    "layer.macWiFi": ("Mac's Wi-Fi", "Wi-Fi del Mac"),
    "layer.internet": ("Internet", "Internet"),
    "layer.mac": ("This Mac", "Questo Mac"),

    # Checklist
    "checklist.locationServices.title": ("Location Services off while gaming", "Localizzazione disattivata mentre giochi"),
    "checklist.locationServices.help": ("Location makes the Wi-Fi scan for networks, which pauses it. Or switch off just System Services → Networking & Wireless.", "La localizzazione fa cercare reti al Wi-Fi, che si ferma. In alternativa disattiva solo Servizi di sistema → Rete e wireless."),
    "checklist.airDrop.title": ("AirDrop set to No One", "AirDrop impostato su Nessuno"),
    "checklist.airDrop.help": ("AirDrop shares the Wi-Fi radio and pauses it to look for nearby devices.", "AirDrop condivide la radio Wi-Fi e la ferma per cercare dispositivi vicini."),
    "checklist.handoff.title": ("Handoff off", "Handoff disattivato"),
    "checklist.handoff.help": ("Handoff uses the same radio as AirDrop.", "Handoff usa la stessa radio di AirDrop."),
    "checklist.universalControl.title": ("Universal Control off", "Controllo universale disattivato"),
    "checklist.universalControl.help": ("It keeps the AirDrop radio busy too.", "Anche questo tiene occupata la radio di AirDrop."),
    "checklist.browserEnergySaver.title": ("Browser energy saver off", "Risparmio energetico del browser disattivato"),
    "checklist.browserEnergySaver.help": ("In Chrome: Settings → Performance → Energy Saver. It lowers the frame rate.", "In Chrome: Impostazioni → Prestazioni → Risparmio energetico. Riduce i fotogrammi."),
    "checklist.streamQuality.title": ("Stream quality set to the highest", "Qualità dello streaming al massimo"),
    "checklist.streamQuality.help": ("In the game service's settings: the highest resolution and bitrate your line allows.", "Nelle impostazioni del servizio di gioco: la risoluzione e il bitrate più alti che la linea permette."),
    "checklist.streamIPv6.title": ("Prefer IPv6 if offered", "Preferisci IPv6 se disponibile"),
    "checklist.streamIPv6.help": ("If your provider uses carrier-grade NAT, IPv6 skips it.", "Se il provider usa il CGNAT, IPv6 lo evita."),
    "checklist.controllerUSB.title": ("Controller on a USB cable", "Controller collegato via USB"),
    "checklist.controllerUSB.help": ("Less input delay than Bluetooth, and Bluetooth shares the Wi-Fi radio.", "Meno ritardo del Bluetooth, che condivide la radio Wi-Fi."),

    # Details keys
    "detail.rssi": ("Signal", "Segnale"),
    "detail.channel": ("Channel", "Canale"),
    "detail.rate": ("Link rate", "Velocità del collegamento"),
    "detail.avg": ("Average", "Media"),
    "detail.max": ("Worst", "Peggiore"),
    "detail.loss": ("Lost", "Persi"),
    "detail.down": ("Download", "Download"),
    "detail.up": ("Upload", "Upload"),
    "detail.rise": ("Latency under load", "Latenza sotto carico"),
    "detail.now": ("Now", "Ora"),
    "detail.usual": ("Usual", "Di solito"),
    "detail.thermal": ("Temperature", "Temperatura"),
    "detail.cpu": ("CPU", "CPU"),
    "detail.battery": ("Battery", "Batteria"),
    "detail.running": ("Running", "In esecuzione"),
    "detail.open": ("Still open", "Ancora da fare"),
    "detail.skipped": ("Skipped", "Saltato"),

    # UI
    "ui.tab.check": ("Check", "Controllo"),
    "ui.tab.checklist": ("Checklist", "Checklist"),
    "ui.tab.history": ("History", "Cronologia"),
    "ui.checkNow": ("Check now", "Controlla ora"),
    "ui.checkAgain": ("Check again", "Controlla di nuovo"),
    "ui.checking": ("Checking…", "Controllo in corso…"),
    "ui.playOn": ("Play on %@", "Gioca su %@"),
    "ui.playAnywayOn": ("Play anyway on %@", "Gioca comunque su %@"),
    "ui.gameMode": ("Game Mode", "Modalità gioco"),
    "ui.gameMode.help": ("Switches off AirDrop, Handoff and Universal Control, keeps the Mac awake, pauses Time Machine and quits apps that get in the way. Turning it off puts every setting back. Asks for your password once.", "Spegne AirDrop, Handoff e Controllo universale, tiene sveglio il Mac, mette in pausa Time Machine e chiude le app che disturbano. Disattivandola, tutte le impostazioni tornano com'erano. Chiede la password una volta."),
    "ui.gameMode.starting": ("Turning on…", "Attivazione…"),
    "ui.gameMode.stopping": ("Turning off…", "Disattivazione…"),
    "ui.gameMode.leftOn": ("Game Mode was left on. Turn it off?", "La Modalità gioco è rimasta attiva. Vuoi disattivarla?"),
    "ui.gameMode.turnOff": ("Turn off", "Disattiva"),
    "ui.gameMode.failed": ("Game Mode couldn't start.", "Impossibile attivare la Modalità gioco."),
    "ui.lastCheck": ("Last checked", "Ultimo controllo"),
    "ui.details": ("Details", "Dettagli"),
    "ui.openSettings": ("Open Settings", "Apri Impostazioni"),
    "ui.detected": ("Detected", "Rilevato"),
    "ui.history.empty": ("No checks yet. Your checks and game sessions appear here.", "Nessun controllo ancora. Qui compariranno controlli e sessioni di gioco."),
    "ui.history.export": ("Export CSV…", "Esporta CSV…"),
    "ui.history.delete": ("Delete All Data…", "Elimina tutti i dati…"),
    "ui.history.deleteConfirm": ("Delete every saved check and session? This can't be undone.", "Eliminare tutti i controlli e le sessioni salvati? Non si può annullare."),
    "ui.history.deleteButton": ("Delete", "Elimina"),
    "ui.cancel": ("Cancel", "Annulla"),
    "ui.session": ("Game session", "Sessione di gioco"),
    "ui.session.calm": ("No hiccups.", "Nessun intoppo."),
    "ui.session.hiccups": ("%lld hiccups", "%lld intoppi"),
    "ui.live.title": ("Live", "In diretta"),
    "ui.live.router": ("Router", "Router"),
    "ui.live.server": ("Game server", "Server di gioco"),
    "ui.live.off": ("Turn on Game Mode to watch the connection while you play.", "Attiva la Modalità gioco per controllare la connessione mentre giochi."),
    "ui.live.noEvents": ("No hiccups so far.", "Nessun intoppo finora."),
    "ui.openApp": ("Open Game Ready", "Apri Game Ready"),
    "ui.quit": ("Quit", "Esci"),
    "ui.settings.browser": ("Browser for Play", "Browser per Gioca"),
    "ui.settings.speed": ("Include a speed test in each check", "Includi un test di velocità in ogni controllo"),
    "ui.settings.speed.help": ("It fills your whole internet line for about 20 seconds.", "Occupa tutta la linea internet per circa 20 secondi."),
    "ui.settings.quitApps": ("Game Mode quits these apps", "La Modalità gioco chiude queste app"),
    "ui.settings.about": ("About", "Informazioni"),
    "ui.settings.privacy": ("Nothing leaves your Mac except the test traffic to the speed-test and latency servers. No accounts, no analytics.", "Dal Mac esce solo il traffico di test verso i server di velocità e latenza. Nessun account, nessuna statistica."),
    "ui.settings.why": ("Cloud gaming lags for many reasons: the Mac's own Wi-Fi, the household line, or the game's servers. Game Ready tells you which one, before you start and while you play.", "Il cloud gaming rallenta per tanti motivi: il Wi-Fi del Mac, la linea di casa o i server del gioco. Game Ready ti dice quale, prima di iniziare e mentre giochi."),
    "ui.settings.platform": ("Gaming service", "Servizio di gioco"),
    "ui.xcloud.tune": ("Game Mode also tunes Better xCloud", "La Modalità gioco regola anche Better xCloud"),
    "ui.xcloud.tune.help": ("Sets the highest bitrate, the high H.264 profile and Prefer IPv6, and puts your own settings back when Game Mode goes off. Needs an open xbox.com tab and, in the browser, Allow JavaScript from Apple Events.", "Imposta il bitrate massimo, il profilo H.264 alto e Preferisci IPv6, e ripristina le tue impostazioni quando la Modalità gioco si spegne. Serve una scheda xbox.com aperta e, nel browser, Consenti JavaScript dagli Apple Events."),
    "ui.xcloud.refresh": ("Refresh", "Aggiorna"),
    "ui.xcloud.unknown": ("Not read yet. Open xbox.com and press Refresh.", "Non ancora letto. Apri xbox.com e premi Aggiorna."),
    "ui.xcloud.notInstalled": ("Better xCloud isn't installed in this browser, or hasn't saved any settings yet.", "Better xCloud non è installato in questo browser, o non ha ancora salvato impostazioni."),
    "ui.xcloud.noTab": ("Open xbox.com in the browser so Game Ready can read Better xCloud's settings.", "Apri xbox.com nel browser così Game Ready può leggere le impostazioni di Better xCloud."),
    "ui.xcloud.jsDisabled": ("The browser blocks this. In Chrome or Edge: View → Developer → Allow JavaScript from Apple Events. In Safari: Develop → Allow JavaScript from Apple Events.", "Il browser lo blocca. In Chrome o Edge: Visualizza → Sviluppatore → Consenti JavaScript dagli Apple Events. In Safari: Sviluppo → Consenti JavaScript dagli Apple Events."),
    "ui.xcloud.notAllowed": ("macOS didn't allow Game Ready to control the browser. Turn it on in System Settings → Privacy & Security → Automation.", "macOS non ha permesso a Game Ready di controllare il browser. Attivalo in Impostazioni di Sistema → Privacy e sicurezza → Automazione."),
    "ui.xcloud.browserClosed": ("The browser isn't open.", "Il browser non è aperto."),
    "ui.xcloud.failed": ("Couldn't change Better xCloud's settings. Nothing was left half-changed.", "Impossibile modificare le impostazioni di Better xCloud. Niente è rimasto a metà."),
    "ui.xcloud.matches": ("Already set: highest bitrate, high profile, Prefer IPv6.", "Già impostato: bitrate massimo, profilo alto, Preferisci IPv6."),
    "ui.xcloud.differs": ("Not tuned yet. Turn on \"Game Mode also tunes Better xCloud\" in Settings, or change it yourself.", "Non ancora regolato. Attiva \"La Modalità gioco regola anche Better xCloud\" nelle Impostazioni, o cambialo tu."),
    "ui.xcloud.applied": ("Tuned for this session. Your own settings come back when Game Mode goes off.", "Regolato per questa sessione. Le tue impostazioni tornano quando la Modalità gioco si spegne."),
    "ui.xcloud.restorePending": ("Your Better xCloud settings will be put back next time xbox.com is open.", "Le tue impostazioni di Better xCloud verranno ripristinate la prossima volta che apri xbox.com."),
    "ui.changes.cannotRead": ("Couldn't read the current %@ setting, so nothing was changed.", "Impossibile leggere l'impostazione %@ attuale, quindi non è stato cambiato nulla."),
    "ui.changes.cannotSave": ("Couldn't save the undo plan, so nothing was changed.", "Impossibile salvare il piano di ripristino, quindi non è stato cambiato nulla."),
    "ui.changes.unreadablePlan": ("The undo plan from an earlier session can't be read, so nothing was changed. It's kept in Application Support/Game Ready/restore-plan.json.", "Il piano di ripristino di una sessione precedente non è leggibile, quindi non è stato cambiato nulla. È conservato in Application Support/Game Ready/restore-plan.json."),
    "speed.tooSoon": ("Ran less than 2 minutes ago", "Eseguito meno di 2 minuti fa"),
}
